services:
  - type: web
    name: request-word-meaning
    env: docker
    plan: free
    repo: https://github.com/Adler-Pereira/requestWordMeaning
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /
