services:
  - type: web
    name: springboot-app
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/requestWordMeaning-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: PORT
        value: 8080
    plan: free
